### PR TITLE
docs(tutorial): new tutorial template to make OSS contributors happen more easily

### PR DESCRIPTION
**Pull request by barriebyron**
This templates README and this tutorial template will provide a working structure for new tutorials.
We have so many awesome content development opportunities and a whole universe of contributors that we can enable with the easy onboarding and structure of a tutorial.
For example, wouldn't it be awesome if open source contributors were able to deliver some of the How the hell series? https://github.com/cosmos/sdk-tutorials/issues/579 

this template is a companion to https://github.com/cosmos/sdk-tutorials/blob/master/templates/concept_template.md and follows the templates that I created for Starport docs https://github.com/tendermint/starport/tree/develop/docs/contributing/templates 

Open for suggestions!

### CODE REVIEW

**Comment by barriebyron** [comment]
do we need a CODEOWNERS file for this repo? I always wonder who can help me here. I'm willing to ask and create the file @okwme 
who is our point person here?

**Review by toschdev — APPROVED** [review]
Amazing 🙏🤩

**Comment by barriebyron** [comment]
because @robert-zaremba is an awesome technical content advocate, I added as a reviewer to get some traction (we do have slow PR approvals for the sdk-tutorials repo... how can we improve?)

**Review by fadeev — APPROVED** [review]
tbh I think one review for tutorials should be enough, unless someone elects themselves to become a codeowner for sdk-tutorials.

**Pull request merged**
