### PR TITLE
Fix deprecated Starport command in IBC tutorial and add runnable codebase

### PR DESCRIPTION
**Pull request by jerryleooo**
Fix deprecated Starport command in IBC tutorial and add runnable codebase

### CODE REVIEW

**Comment by toschdev** [comment]
Thanks a lot for your contribution @jerryleooo . We appreciate your input and work.

Could you please make sure to put the version of starport that you used at the beginning of the tutorial?
Thanks 🙏

**Comment by jerryleooo** [comment]
@toschdev sure

**Comment by toschdev** [comment]
Thanks, currently line 45 it is where we mention the version, this would be the right place to change the version accordingly.

**Comment by jerryleooo** [comment]
@toschdev welcome, done already

**Comment by jerryleooo** [comment]
@toschdev just wondering, if I have a workable codebase that followed this tutorial, if it is OK to paste the link in this tutorial? So other users can just download the code and run it.

**Comment by toschdev** [comment]
We have done it previously that there is an extra directory next to the tutorial in this repository. Please check voter or blog tutorial. Feel free to add your source code in a similar way 👍
Please do not forget the Makefile as well.

**Comment by jerryleooo** [comment]
cool, I will convert this into a draft first and add the code part

**Comment by jerryleooo** [comment]
Hi @toschdev , I just found including the codebase would involve a lot of changes and is hard to review, so I plan to separate the doc changing and codebase adding into 2 PRs, any ideas?

**Comment by toschdev** [comment]
Two PRs would also work. It is fine in one though, I will review the codebase

**Comment by nooomski** [comment]
Hey, much of this content have been replaced by the Cosmos Academy or exist in some other form on https://github.com/tendermint/starport
I'm going to close this PR. Feel free to reopen and ping me if you have any concerns.

**Pull request closed without merging**
