### PR TITLE
Updates for Starport v0.16

### PR DESCRIPTION
**Pull request by fadeev**
In Starport v0.16 (the next release) the `type` scaffolding logic has been improved, so that types can be modified from proto files without modifying the source code. This affects the "IBC Hello world" tutorial, so this PR makes sure that this tutorial will be compatible with the new version of Starport.

Merge once v0.16 is released.

Relevant: https://github.com/tendermint/starport/pull/988

cc @lubtd

### CODE REVIEW

**Comment by lubtd** [comment]
Thanks for the changes!

**Comment by toschdev** [comment]
Thanks @fadeev for preparing this

**Comment by lubtd** [comment]
Updated with the `--no-message` options of scaffolding commands

**Comment by lubtd** [comment]
Added the `source-gas-price` and `target-gas-price` options in the `relayer configure` command for IBC tutorials. Thanks @noandrea for having noticed this change.

Added stake token for the faucet in the configuration files.

**Comment by lubtd** [comment]
Added the new `--source-prefix` and `--target-prefix` flags to `starport configure` command

**Review by barriebyron — APPROVED** [review]
thanks for these awesome v0.16 tutorial updates @fadeev 
I made a few minor editorial changes along the way

**Review by toschdev — APPROVED** [review]

**Pull request merged**
