### PR TITLE
Code/structure/compile fixes

### PR DESCRIPTION
**Pull request by quantaf1re**
Changed:

Spelling
 - Mentioning that nothing is supposed to be cloned
 - Saying to create files instead of open them when they don't exist
 - Added the comma so this can compile:
```
    var app = &helloChainApp{
        appStarter,
    }
```
 - Corrected file path to x/greeter/client/cli/query.go in client.md

### CODE REVIEW

**Comment by marbar3778** [comment]
Could you resolve the merge conflicts and then we can merge

**Comment by hschoenburg** [comment]
@quantaf1re can you make sure to check the "Allow edits from maintainers" check box on your PR? Then I can reselve these conflicts and get you PR merged promptly. Thank you for the contribution.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by quantaf1re** [comment]
I just saw these comments sorry
Hmm, "Allow edits from maintainers" is already checked

**Comment by marbar3778** [comment]
@hschoenburg you can set his repo to a remote and pull the branch then push it yourself, I find this easiest

**Comment by hschoenburg** [comment]
Thanks @quantaf1re !

**Pull request merged**
