### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by ekkis**
v0.16.2 does not support `--version` but `version`

### CODE REVIEW

**Review by barriebyron — APPROVED** [review]
thanks @ekkis for this fix!

**Comment by barriebyron** [comment]
oof I introduced this error, and fortunately Erick caught it here, another approval please @soniasingla

**Review by soniasingla — COMMENTED** [review]
@barriebyron actually `.17` also doesn't support `--version`, are we depreciating this @fadeev?

**Comment by fadeev** [comment]
Screenshot 2021-09-15 at 19 50 37

**Comment by fadeev** [comment]
I think we always had `starport version`.

**Comment by barriebyron** [comment]
ha!

**Review by toschdev — APPROVED** [review]

**Review by soniasingla — APPROVED** [review]

**Comment by ekkis** [comment]
honestly, it's more standard to use `--version`

**Comment by toschdev** [comment]
> honestly, it's more standard to use `--version`

Probably not in the Go world

**Comment by ekkis** [comment]
> > honestly, it's more standard to use `--version`
> 
> Probably not in the Go world

it's a CLI i.e. bash or some kind of shell.  in shells it is a convention for applications to offer `--version` or `-V`, as it is conventional to offer `--help` or `-?`

**Pull request merged**
