### PR TITLE
Minor fixes, including linting on middleware sections.

### PR DESCRIPTION
**Pull request by xavierlepretre**
Documentation content update for the IBC middleware sections.

This PR does some linting and adds a couple comments.

### R1: Internal review (B9lab)

- Technical review
  - [x] requested
  - [x] completed
- Language review
  - [x] requested
  - [x] completed
- Technical platform review (remove if not required)
  - [ ] requested
  - [ ] completed

### R2: External review

- Technical review
  - [x] requested
  - [ ] completed
- Language review
  - [ ] requested
  - [ ] completed

### R3: Internal QA review (B9lab)

- Technical review
  - [ ] requested
  - [ ] completed
- Language review
  - [ ] requested
  - [ ] completed

### R4: Final external QA review

- Technical review
  - [ ] requested
  - [ ] completed
- Language review
  - [ ] requested
  - [ ] completed

### RC: Release Candidate

- [ ] Ready to be merged

### CODE REVIEW

**Comment by tmsdkeys** [comment]
Most of this LGTM @xavierlepretre , I have a [draft PR open on ibc-go](https://github.com/cosmos/ibc-go/pull/3134) that addresses some of this as well. We'll finish it later this week and then I will make sure to sync here as well

**Review by murataniloener — APPROVED** [review]
lgtm!

**Comment by xavierlepretre** [comment]
> Most of this LGTM @xavierlepretre , I have a [draft PR open on ibc-go](https://github.com/cosmos/ibc-go/pull/3134) that addresses some of this as well. We'll finish it later this week and then I will make sure to sync here as well

@tmsdkeys I see the other PR is merged, so I guess it is ok to merge now?

**Comment by tmsdkeys** [comment]
@xavierlepretre think the changes made there still could be reflected here. I can follow up on that one of the following days

**Comment by CitMC** [comment]
@xavierlepretre should we close this PR?

**Comment by xavierlepretre** [comment]
I think it should be merged after review.

**Review by AndrewB9lab — APPROVED** [review]
Language review on edits complete.

**Review by CitMC — APPROVED** [review]

**Pull request merged**
