### PR TITLE
update the number of active validators

### PR DESCRIPTION
**Pull request by mishcheek**
The number of active validators should be updated to 175 as per passed proposal #66. This PR updates the content in [academy/2-cosmos-concepts/1-architecture.md](https://github.com/cosmos/sdk-tutorials/pull/1305/files#diff-3780f91a7ea4e9609257a49105dd26dfd19a8bc979da21acde25c574374995bf) to reflect this.

### Change scope

The changes in this Pull Request include (please tick all that apply):

* [ ] Small language/grammar fixes
* [x] Small content fixes 
* [ ] Addition of new content
* [ ] Sample code/command updates
* [ ] Platform fixes
* [ ] Other

### CODE REVIEW

**Comment by xavierlepretre** [comment]
@CitMC @rob-Hitchens What I see also is that perhaps now would be a good time for the content to stop conflating Cosmos Hub particulars from the defaults (or limits) of Cosmos SDK.

**Review by AndrewB9lab — APPROVED** [review]
Language review "okay"

**Review by CitMC — APPROVED** [review]
Can be merged

**Comment by coldice** [comment]
Looks good, @mishcheek thank you for your contribution!

**Review by coldice — APPROVED** [review]

**Pull request merged**
