### PR TITLE
docs:Add Korean Translate

### PR DESCRIPTION
**Pull request by MiryangJung**
I translated README & tutorial 00~02

### CODE REVIEW

**Comment by marbar3778** [comment]
Is this still in WIP phase or completed?

**Comment by MiryangJung** [comment]
I translate en to ko Just  Tutorial 00~02 And Reame.md

**Comment by marbar3778** [comment]
Ah okay, I was wondering since 02 is still predominately in English, if this is purposeful then I would ask if the whole file could be done or that it be removed from the kr section

**Comment by marbar3778** [comment]
closing as there hasn't been a response to why 02 is partially translated. If you would like to complete the PR then you can reopen this PR. We would love your contribution!!

**Pull request closed without merging**
